export const typesOfMaterials = [
  'Addendum',
  'An Analysis',
  'An Appraisal',
  'Article',
  'Banner',
  'Biography',
  'Birth Notice',
  'Blog',
  'Brief',
  'Caption',
  'Chronology',
  'Column',
  'Correction',
  'Economic Analysis',
  'Editorial',
  'Editorial Cartoon',
  'First Chapter',
  'Front Page',
  'Glossary',
  'Interactive Feature',
  'Interactive Graphic',
  'Interview',
  'Letter',
  'List',
  'Marriage Announcement',
  'Military Analysis',
  'News',
  'News Analysis',
  'Newsletter',
  'Obituary',
  'Obituary (Obit)',
  'Op-Ed',
  'Paid Death Notice',
  'Postscript',
  'Premium',
  'Question',
  'Quote',
  'Recipe',
  'Review',
  'Schedule',
  'SectionFront',
  'Series',
  'Slideshow',
  'Special Report',
  'Statistics',
  'Summary',
  'Text',
  'Video',
  'Web Log',
]
